export enum ErrorCode {
    DATABASE_ERROR,
    INTERNAL_SYSTEM_ERROR,
    ID_NOT_PROVIDED,
    OPERATION_NOT_SUPPORTED,
    INVALID_ARGUMENT,
    ENTITY_NOT_FOUND,
    MODIFY_DELETED_ENTITY,
    ENTITY_DUPLICATE,
    VALIDATION,
    INSUFFICIENT_PERMISSION,
    THIRD_PARTY_SERVICE_ERROR,
    NOT_IMPLEMENTED,
    USER_NOT_PROVIDED,
  }
  